# This file is managed by `git_helper`. Don't edit it directly

language: python
dist: xenial
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - 'pypy3'

install:

  - pip install pip  --upgrade
  - pip install tox tox-travis
  - pip install coveralls

script:
  - tox
after_success:
  - coveralls


stages:
  - test
  - deploy_pypi
  - deploy_conda
  - deploy_releases

jobs:
  include:
    - stage: deploy_pypi
      python: "3.6"
      script: skip
      deploy:
        on:
          tags: true
          repo: domdfcoding/singledispatch-json
        provider: pypi
        user: "DomDF"
        password:
          secure: VYdUaqcgqHZO4P/TIVwfsr1BkRaCF+WYnk1p0PHJ2AbUym+tXxzjjb1driy3o7r1Y8pkfr4cetRCj7Uvjf/hEe4kzI+i8ktgnL3WHtZiKhAt0jgb2/Yyj31Xi9pZJiUuOR9l4bt+9jecTw1xf0oa8/KM092Y0hk/jaHs8h8ShKBkiNp4M+kX+FziMkSVA+ZrvQ77PrM90QrMDwN4GHzKfMcJm0l6Qqs01bL1/sI7zyYM47QuJ5OxdP1+cX5SNwMOW8IgHGz0D9xWtTjZt9vO8e4jSF7scojPM3Q1HiS6x0arHcUaU+X57G7p9RxWSG3ihOFGiWFmMna39bT57T5KnlHSV5Lre3sDiTAvRJ3hcQwTfGXJCx0Nc7ZqD9sPT4dsYG56+UnEtWbgb1ELQcTg+uRtIKXZCpHegjn4BDrzPDvC5fT11VhBqMLg5UsuBE+thHhVmjntsYPgYmHwspl54w8S8rEq8NjT5nEvH+Pw/jrw2eeb8/ltPYfr7Dr2Axx6OmGexLX/Rok0dg4tlYZlzSHS5JfJvHUKH9S32oCa6A0XZQO7oTZJrT6q4b9AICrUcUTpBvHE8qAxycF7sfZ15riZ5nlxRSvsJeDnF31MfJqftFFfFhOQOGhzHHbwuQ7BMe5Bqq0jaIdW92k3o0tBoYB71lPD36ZAl3FfuZY3hDE=
        distributions: "sdist bdist_wheel"
        skip_existing: true
    - stage: deploy_conda
      python: "3.6"
      addons:
        apt:
          update: true
      install:
        - pip install rst2txt yolk3k
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - chmod +x .ci/travis_deploy_conda.sh
      script: skip
      deploy:
        on:
          repo: domdfcoding/singledispatch-json
        provider: script
        script: .ci/travis_deploy_conda.sh || travis_terminate 1;

    - stage: deploy_releases
      python: "3.6"
      install:
        - pip install PyGithub requests
      script: skip
      deploy:
        on:
          repo: domdfcoding/singledispatch-json
        provider: script
        script: python .ci/copy_pypi_2_github.py || travis_terminate 1;
